### ISSUE TITLE
No module named decompanion

### ISSUE THREAD

**Issue by b33fstrogan0ff** [philsajdak/decyx#1]
Hey, just tried installing this plugin. Followed the instructions but when I run it I'm getting the following error in the Ghidra console: 
```
Traceback (most recent call last):
  File "/home/user/Tools/ghidra_plugins/decyx/Decyx/Decyx.py", line 16, in <module>
    from decyx.gui import *
  File "/home/user/Tools/ghidra_plugins/decyx/Decyx/decyx/gui.py", line 3, in <module>
    from decompanion.dialogs.suggestion_dialog import show_suggestion_dialog
ImportError: No module named decompanion
```
Running Ghidra 11.2.

**Comment by mosimo** [comment]
Very quick fix without having to change any code:
Copy the `decyx` folder where `Decyx.py` is and call it `decompanion`

![image](https://github.com/user-attachments/assets/0829cb43-84d2-454b-8bea-228c10d51ce3)

**Comment by b33fstrogan0ff** [comment]
Thanks that did the trick!

**Comment by philsajdak** [comment]
Sorry, looks like I somehow forgot to fix some of the renaming in some of the files back when the project was still called Decompanion. Should be fixed now.
